// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQ0pI-HrDisFrJFgZNj_TNFW_6WiXnyA',
    appId: '1:191792249819:web:fc607daee329f6a5c745fe',
    messagingSenderId: '191792249819',
    projectId: 'philosocratic-40f10',
    authDomain: 'philosocratic-40f10.firebaseapp.com',
    storageBucket: 'philosocratic-40f10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFJZKAQrqViRz8I5dXFFIlPtK_N9pLn4',
    appId: '1:191792249819:android:20b51b5750fc8baec745fe',
    messagingSenderId: '191792249819',
    projectId: 'philosocratic-40f10',
    storageBucket: 'philosocratic-40f10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALdb54e1FGtIYMJG5Pl_syqawOKL1L9rk',
    appId: '1:191792249819:ios:f309fe82381d25e7c745fe',
    messagingSenderId: '191792249819',
    projectId: 'philosocratic-40f10',
    storageBucket: 'philosocratic-40f10.appspot.com',
    iosClientId: '191792249819-mek86qcmtpfniq10864k5s3s0tvj4u7f.apps.googleusercontent.com',
    iosBundleId: 'com.philosocratic.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALdb54e1FGtIYMJG5Pl_syqawOKL1L9rk',
    appId: '1:191792249819:ios:f309fe82381d25e7c745fe',
    messagingSenderId: '191792249819',
    projectId: 'philosocratic-40f10',
    storageBucket: 'philosocratic-40f10.appspot.com',
    iosClientId: '191792249819-mek86qcmtpfniq10864k5s3s0tvj4u7f.apps.googleusercontent.com',
    iosBundleId: 'com.philosocratic.app',
  );
}
